# Generated by Django 2.1 on 2018-08-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(default='Sin ubicacion', max_length=100)),
                ('local_envio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envio_envio', to='local.Local')),
                ('local_llegada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envio_llegada', to='local.Local')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('descripcion', models.CharField(default='Descripcion del ingreso', max_length=200)),
                ('local', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='local.Local')),
                ('proveedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='proveedor.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('stock_minimo', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('cantidad', models.PositiveIntegerField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Stock'),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='id_ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Ingreso'),
        ),
        migrations.AddField(
            model_name='detalleingreso',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Producto'),
        ),
    ]
