# Generated by Django 2.1 on 2018-08-12 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180812_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='descripcion',
            field=models.CharField(default='Descripcion del ingreso', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='local.Local'),
        ),
    ]
