# Generated by Django 2.1 on 2018-08-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20180815_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='local_envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envio_envio', to='local.Local'),
        ),
    ]
