# Generated by Django 2.1 on 2018-08-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20180812_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='proveedor.Proveedor'),
        ),
    ]
