# Generated by Django 2.1 on 2018-08-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180812_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='local_llegada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='local.Local'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='local.Local'),
        ),
    ]
