# Generated by Django 2.1 on 2018-08-17 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20180815_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='local_llegada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envio_llegada', to='local.Local'),
        ),
    ]
