# Generated by Django 2.1 on 2018-08-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20180812_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
