# Generated by Django 2.1 on 2018-08-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_auto_20180813_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='descripcion',
            field=models.CharField(default='Descripcion del ingreso', max_length=200),
        ),
    ]
