# Generated by Django 2.1 on 2018-08-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_auto_20180813_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleingreso',
            name='codigo_producto',
        ),
        migrations.AddField(
            model_name='stock',
            name='codigo',
            field=models.CharField(default=0, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
