# Generated by Django 2.1 on 2018-08-15 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20180813_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleenvio',
            name='id_envio',
        ),
        migrations.RemoveField(
            model_name='detalleenvio',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='local_llegada',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='local',
        ),
        migrations.DeleteModel(
            name='DetalleEnvio',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
