# Generated by Django 2.1 on 2018-08-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20180814_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='codigo',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
