# Generated by Django 2.1 on 2018-08-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Locales',
                'ordering': ['nombre'],
            },
        ),
    ]
