# Generated by Django 2.1 on 2018-08-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Locales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='StockLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=50, verbose_name='Ubicacion producto')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Local')),
            ],
        ),
    ]
