# Generated by Django 2.1 on 2018-08-15 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocal',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Stock'),
        ),
    ]
