# Generated by Django 2.1 on 2018-08-12 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180812_1700'),
        ('local', '0002_stocklocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocal',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.DetalleIngreso'),
        ),
    ]
