# Generated by Django 2.1 on 2018-08-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_stocklocal_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocal',
            name='ubicacion',
            field=models.CharField(default='Ubicacion', max_length=50),
        ),
        migrations.AlterField(
            model_name='stocklocal',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
