# Generated by Django 2.1 on 2018-08-13 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_auto_20180813_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklocal',
            name='precio_descuento',
        ),
        migrations.RemoveField(
            model_name='stocklocal',
            name='precio_venta',
        ),
        migrations.AlterField(
            model_name='stocklocal',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Stock'),
        ),
        migrations.AlterField(
            model_name='stocklocal',
            name='ubicacion',
            field=models.CharField(default='Ubicacion producto', max_length=50),
        ),
    ]
