# Generated by Django 2.1 on 2018-08-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventarapida_ventarapidadetalle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VentaRapidaDetalle',
        ),
        migrations.AddField(
            model_name='ventarapida',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventarapida',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ventarapida',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ventarapida',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ventarapida',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ventarapida',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='local.StockLocal'),
        ),
    ]
