# Generated by Django 2.1 on 2018-08-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20180817_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventarapida',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
